"use client";
import { useMemo, useState } from "react";
import type { Product } from "@/lib/catalog/types";
import { ProductCard } from "../_components/sections/popular-products";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import Button from "@/components/ui/button";
export default function CatalogGrid({ products }: { products: Product[] }) {
  const [inStock, setInStock] = useState(false);
  const [query, setQuery] = useState(""); const [category, setCategory] = useState(""); const [sort, setSort] = useState("default");
  const filtered = useMemo(() => products.filter((item) => (!inStock || item.stock > 0) && (!category || item.category === category) && `${item.title} ${item.category}`.toLocaleLowerCase("id").includes(query.toLocaleLowerCase("id"))).sort((a, b) => sort === "low" ? a.price - b.price : sort === "high" ? b.price - a.price : a.title.localeCompare(b.title)), [products, query, category, sort, inStock]);
  return <section className="mx-auto max-w-7xl px-4 py-12 lg:px-8"><p className="text-xs uppercase tracking-widest text-secondary">The Alinara Collection</p><h1 className="mt-4 font-display text-4xl lg:text-5xl">Temukan Karya Anda</h1><p className="mt-4 max-w-lg text-sm leading-relaxed text-on-surface-variant">Warna bersahaja, detail istimewa. Pilih yang paling dekat dengan gaya Anda.</p><div className="my-8 grid gap-4 rounded-2xl bg-surface-container-low p-5 sm:grid-cols-[1fr_auto_auto]"><label className="text-xs">Cari produk<Input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Pashmina, voal…" className="mt-2 block w-full rounded-lg border border-outline-variant bg-surface p-3 text-sm" /></label><label className="text-xs">Kategori<Select value={category} onChange={(event) => setCategory(event.target.value)} className="mt-2 block w-full rounded-lg border border-outline-variant bg-surface p-3 text-sm"><option value="">Semua kategori</option>{[...new Set(products.map((item) => item.category))].map((item) => <option key={item}>{item}</option>)}</Select></label><label className="text-xs">Urutkan<Select value={sort} onChange={(event) => setSort(event.target.value)} className="mt-2 block w-full rounded-lg border border-outline-variant bg-surface p-3 text-sm"><option value="default">Nama produk</option><option value="low">Harga terendah</option><option value="high">Harga tertinggi</option></Select></label></div><label className="mb-5 flex w-fit items-center gap-3 text-sm"><Checkbox checked={inStock} onCheckedChange={(checked) => setInStock(checked === true)} />Hanya produk tersedia</label><p aria-live="polite" className="mb-5 text-sm text-on-surface-variant">{filtered.length} karya ditemukan</p><div className="grid grid-cols-2 gap-4 lg:grid-cols-4 lg:gap-6">{filtered.map((product) => <ProductCard key={product.id} product={product} />)}</div>{!filtered.length && <div className="py-16 text-center"><h2 className="font-display text-2xl">Belum ada yang cocok</h2><p className="my-4 text-sm">Coba kata kunci atau kategori lainnya.</p><Button variant="outline" onClick={() => { setQuery(""); setCategory(""); setInStock(false); }}>Reset Filter</Button></div>}</section>;
}
