"use client";
import { useRef, useState, type FormEvent } from "react";
import Link from "next/link";
import Button from "@/components/ui/button";
import { FormField } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Alert } from "@/components/ui/alert";
import { Loader } from "@/components/ui/loader";
import { useCart, formatRupiah } from "@/hooks/use-cart";
export default function CheckoutForm({ enabled, shipping }: { enabled: boolean; shipping: number }) {
  const cart = useCart(); const key = useRef<string | null>(null); const busy = useRef(false);
  const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<{ reference: string; total: number } | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy.current) return; busy.current = true; setPending(true); setError("");
    key.current ??= crypto.randomUUID();
    const input = { ...Object.fromEntries(new FormData(event.currentTarget)), idempotencyKey: key.current, items: cart.items.map(({ id, color, quantity }) => ({ id, color, quantity })) };
    try { const response = await fetch("/api/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data); cart.clear(); }
    catch (error) { setError(error instanceof Error ? error.message : "Koneksi terputus. Coba lagi."); } finally { busy.current = false; setPending(false); }
  }
  if (result) return <section className="mx-auto max-w-xl px-6 py-20 text-center"><span className="inline-grid size-16 place-items-center rounded-full bg-secondary-container text-3xl text-secondary">✓</span><h1 className="mt-6 font-display text-3xl">Pesanan berhasil dicatat</h1><p className="mt-4">Nomor pesanan: <strong>{result.reference}</strong></p><p className="mt-3">Total: {formatRupiah(result.total)}</p><p className="mt-5 text-sm text-on-surface-variant">Simpan nomor ini. Pesanan menunggu konfirmasi admin; belum ada pembayaran yang diproses.</p><Link href="/products" className="mt-8 inline-block text-secondary underline">Kembali ke koleksi</Link></section>;
  return <section className="mx-auto max-w-6xl px-5 py-12"><Link href="/cart" className="text-sm text-secondary">← Kembali ke keranjang</Link><h1 className="mt-6 font-display text-4xl">Detail Pemesanan</h1>{!enabled ? <p className="mt-6 rounded-xl bg-surface-container p-6">Pemesanan sedang dipersiapkan. Produk pilihan Anda tetap tersimpan di keranjang.</p> : !cart.items.length ? <p className="mt-6">Keranjang masih kosong. <Link href="/products" className="underline">Jelajahi koleksi</Link></p> : <form onSubmit={submit} className="mt-8 grid gap-10 lg:grid-cols-[1fr_360px]"><fieldset disabled={pending} className="grid gap-5"><legend className="mb-5 font-display text-xl">Alamat penerima</legend>{[{ name: "name", label: "Nama lengkap", auto: "name" }, { name: "email", label: "Email", type: "email", auto: "email" }, { name: "phone", label: "Nomor telepon", type: "tel", auto: "tel" }, { name: "address", label: "Alamat lengkap", auto: "street-address" }, { name: "city", label: "Kota / Kabupaten", auto: "address-level2" }, { name: "postalCode", label: "Kode pos", auto: "postal-code" }].map((field) => <FormField key={field.name} label={field.label}><Input name={field.name} type={field.type ?? "text"} autoComplete={field.auto} required minLength={field.name === "address" ? 10 : undefined} maxLength={field.name === "address" ? 500 : field.name === "postalCode" ? 5 : 254} pattern={field.name === "postalCode" ? "[0-9]{5}" : undefined} /></FormField>)}</fieldset><aside className="h-fit rounded-2xl bg-surface-container-low p-6"><h2 className="font-display text-xl">Ringkasan Pesanan</h2><ul className="mt-5 space-y-4">{cart.items.map((item) => <li key={`${item.id}:${item.color}`} className="text-sm">{item.product.title}<span className="block text-xs text-on-surface-variant">{item.color} × {item.quantity}</span></li>)}</ul><dl className="mt-6 space-y-3 text-sm"><div className="flex justify-between"><dt>Subtotal</dt><dd>{formatRupiah(cart.total)}</dd></div><div className="flex justify-between"><dt>Ongkos kirim</dt><dd>{formatRupiah(shipping)}</dd></div><div className="flex justify-between border-t border-outline-variant pt-4 font-semibold"><dt>Total</dt><dd>{formatRupiah(cart.total + shipping)}</dd></div></dl><p className="mt-5 text-xs leading-relaxed text-on-surface-variant">Pesanan akan ditinjau admin sebelum pembayaran. Harga dan stok diperiksa kembali saat pesanan dibuat.</p>{error && <Alert role="alert" variant="destructive" className="mt-4">{error}</Alert>}<Button type="submit" disabled={pending} className="mt-5 w-full">{pending && <Loader size="sm" />} {pending ? "Memproses…" : "Buat Pesanan"}</Button></aside></form>}</section>;
}
